name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Archive artifact
      uses: actions/upload-pages-artifact@v3
      with:
        artifact-name: github-pages
        path: dist

  deploy:
    runs-on: windows-latest
    
    permissions:
      contents: write
      pages: write

    needs: build
    steps:

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact-path: dist



